// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

package pb;

public final class PersonOuterClass {
  private PersonOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   * 枚举类型
   * </pre>
   *
   * Protobuf enum {@code pb.PhoneType}
   */
  public enum PhoneType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNKNOWN = 0;</code>
     */
    UNKNOWN(0),
    /**
     * <code>MOBILE = 1;</code>
     */
    MOBILE(1),
    /**
     * <code>HOME = 2;</code>
     */
    HOME(2),
    /**
     * <code>WORK = 3;</code>
     */
    WORK(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNKNOWN = 0;</code>
     */
    public static final int UNKNOWN_VALUE = 0;
    /**
     * <code>MOBILE = 1;</code>
     */
    public static final int MOBILE_VALUE = 1;
    /**
     * <code>HOME = 2;</code>
     */
    public static final int HOME_VALUE = 2;
    /**
     * <code>WORK = 3;</code>
     */
    public static final int WORK_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PhoneType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static PhoneType forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN;
        case 1: return MOBILE;
        case 2: return HOME;
        case 3: return WORK;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<PhoneType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        PhoneType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<PhoneType>() {
            public PhoneType findValueByNumber(int number) {
              return PhoneType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return pb.PersonOuterClass.getDescriptor().getEnumTypes().get(0);
    }

    private static final PhoneType[] VALUES = values();

    public static PhoneType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private PhoneType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:pb.PhoneType)
  }

  public interface PersonOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pb.Person)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 姓名
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <pre>
     * 姓名
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <pre>
     * 年龄
     * </pre>
     *
     * <code>int32 age = 2;</code>
     * @return The age.
     */
    int getAge();

    /**
     * <pre>
     * 电子邮件
     * </pre>
     *
     * <code>repeated string emails = 3;</code>
     * @return A list containing the emails.
     */
    java.util.List<java.lang.String>
        getEmailsList();
    /**
     * <pre>
     * 电子邮件
     * </pre>
     *
     * <code>repeated string emails = 3;</code>
     * @return The count of emails.
     */
    int getEmailsCount();
    /**
     * <pre>
     * 电子邮件
     * </pre>
     *
     * <code>repeated string emails = 3;</code>
     * @param index The index of the element to return.
     * @return The emails at the given index.
     */
    java.lang.String getEmails(int index);
    /**
     * <pre>
     * 电子邮件
     * </pre>
     *
     * <code>repeated string emails = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the emails at the given index.
     */
    com.google.protobuf.ByteString
        getEmailsBytes(int index);

    /**
     * <pre>
     * 电话
     * </pre>
     *
     * <code>repeated .pb.PhoneNumber phones = 4;</code>
     */
    java.util.List<pb.PersonOuterClass.PhoneNumber> 
        getPhonesList();
    /**
     * <pre>
     * 电话
     * </pre>
     *
     * <code>repeated .pb.PhoneNumber phones = 4;</code>
     */
    pb.PersonOuterClass.PhoneNumber getPhones(int index);
    /**
     * <pre>
     * 电话
     * </pre>
     *
     * <code>repeated .pb.PhoneNumber phones = 4;</code>
     */
    int getPhonesCount();
    /**
     * <pre>
     * 电话
     * </pre>
     *
     * <code>repeated .pb.PhoneNumber phones = 4;</code>
     */
    java.util.List<? extends pb.PersonOuterClass.PhoneNumberOrBuilder> 
        getPhonesOrBuilderList();
    /**
     * <pre>
     * 电话
     * </pre>
     *
     * <code>repeated .pb.PhoneNumber phones = 4;</code>
     */
    pb.PersonOuterClass.PhoneNumberOrBuilder getPhonesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code pb.Person}
   */
  public static final class Person extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pb.Person)
      PersonOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Person.newBuilder() to construct.
    private Person(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Person() {
      name_ = "";
      emails_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      phones_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Person();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pb.PersonOuterClass.internal_static_pb_Person_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pb.PersonOuterClass.internal_static_pb_Person_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pb.PersonOuterClass.Person.class, pb.PersonOuterClass.Person.Builder.class);
    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <pre>
     * 姓名
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 姓名
     * </pre>
     *
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AGE_FIELD_NUMBER = 2;
    private int age_;
    /**
     * <pre>
     * 年龄
     * </pre>
     *
     * <code>int32 age = 2;</code>
     * @return The age.
     */
    @java.lang.Override
    public int getAge() {
      return age_;
    }

    public static final int EMAILS_FIELD_NUMBER = 3;
    private com.google.protobuf.LazyStringList emails_;
    /**
     * <pre>
     * 电子邮件
     * </pre>
     *
     * <code>repeated string emails = 3;</code>
     * @return A list containing the emails.
     */
    public com.google.protobuf.ProtocolStringList
        getEmailsList() {
      return emails_;
    }
    /**
     * <pre>
     * 电子邮件
     * </pre>
     *
     * <code>repeated string emails = 3;</code>
     * @return The count of emails.
     */
    public int getEmailsCount() {
      return emails_.size();
    }
    /**
     * <pre>
     * 电子邮件
     * </pre>
     *
     * <code>repeated string emails = 3;</code>
     * @param index The index of the element to return.
     * @return The emails at the given index.
     */
    public java.lang.String getEmails(int index) {
      return emails_.get(index);
    }
    /**
     * <pre>
     * 电子邮件
     * </pre>
     *
     * <code>repeated string emails = 3;</code>
     * @param index The index of the value to return.
     * @return The bytes of the emails at the given index.
     */
    public com.google.protobuf.ByteString
        getEmailsBytes(int index) {
      return emails_.getByteString(index);
    }

    public static final int PHONES_FIELD_NUMBER = 4;
    private java.util.List<pb.PersonOuterClass.PhoneNumber> phones_;
    /**
     * <pre>
     * 电话
     * </pre>
     *
     * <code>repeated .pb.PhoneNumber phones = 4;</code>
     */
    @java.lang.Override
    public java.util.List<pb.PersonOuterClass.PhoneNumber> getPhonesList() {
      return phones_;
    }
    /**
     * <pre>
     * 电话
     * </pre>
     *
     * <code>repeated .pb.PhoneNumber phones = 4;</code>
     */
    @java.lang.Override
    public java.util.List<? extends pb.PersonOuterClass.PhoneNumberOrBuilder> 
        getPhonesOrBuilderList() {
      return phones_;
    }
    /**
     * <pre>
     * 电话
     * </pre>
     *
     * <code>repeated .pb.PhoneNumber phones = 4;</code>
     */
    @java.lang.Override
    public int getPhonesCount() {
      return phones_.size();
    }
    /**
     * <pre>
     * 电话
     * </pre>
     *
     * <code>repeated .pb.PhoneNumber phones = 4;</code>
     */
    @java.lang.Override
    public pb.PersonOuterClass.PhoneNumber getPhones(int index) {
      return phones_.get(index);
    }
    /**
     * <pre>
     * 电话
     * </pre>
     *
     * <code>repeated .pb.PhoneNumber phones = 4;</code>
     */
    @java.lang.Override
    public pb.PersonOuterClass.PhoneNumberOrBuilder getPhonesOrBuilder(
        int index) {
      return phones_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (age_ != 0) {
        output.writeInt32(2, age_);
      }
      for (int i = 0; i < emails_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, emails_.getRaw(i));
      }
      for (int i = 0; i < phones_.size(); i++) {
        output.writeMessage(4, phones_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (age_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, age_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < emails_.size(); i++) {
          dataSize += computeStringSizeNoTag(emails_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getEmailsList().size();
      }
      for (int i = 0; i < phones_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, phones_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pb.PersonOuterClass.Person)) {
        return super.equals(obj);
      }
      pb.PersonOuterClass.Person other = (pb.PersonOuterClass.Person) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (getAge()
          != other.getAge()) return false;
      if (!getEmailsList()
          .equals(other.getEmailsList())) return false;
      if (!getPhonesList()
          .equals(other.getPhonesList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + AGE_FIELD_NUMBER;
      hash = (53 * hash) + getAge();
      if (getEmailsCount() > 0) {
        hash = (37 * hash) + EMAILS_FIELD_NUMBER;
        hash = (53 * hash) + getEmailsList().hashCode();
      }
      if (getPhonesCount() > 0) {
        hash = (37 * hash) + PHONES_FIELD_NUMBER;
        hash = (53 * hash) + getPhonesList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pb.PersonOuterClass.Person parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.PersonOuterClass.Person parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.PersonOuterClass.Person parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.PersonOuterClass.Person parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.PersonOuterClass.Person parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.PersonOuterClass.Person parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.PersonOuterClass.Person parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pb.PersonOuterClass.Person parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static pb.PersonOuterClass.Person parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static pb.PersonOuterClass.Person parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pb.PersonOuterClass.Person parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pb.PersonOuterClass.Person parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pb.PersonOuterClass.Person prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pb.Person}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pb.Person)
        pb.PersonOuterClass.PersonOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pb.PersonOuterClass.internal_static_pb_Person_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pb.PersonOuterClass.internal_static_pb_Person_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pb.PersonOuterClass.Person.class, pb.PersonOuterClass.Person.Builder.class);
      }

      // Construct using pb.PersonOuterClass.Person.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";

        age_ = 0;

        emails_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (phonesBuilder_ == null) {
          phones_ = java.util.Collections.emptyList();
        } else {
          phones_ = null;
          phonesBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pb.PersonOuterClass.internal_static_pb_Person_descriptor;
      }

      @java.lang.Override
      public pb.PersonOuterClass.Person getDefaultInstanceForType() {
        return pb.PersonOuterClass.Person.getDefaultInstance();
      }

      @java.lang.Override
      public pb.PersonOuterClass.Person build() {
        pb.PersonOuterClass.Person result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public pb.PersonOuterClass.Person buildPartial() {
        pb.PersonOuterClass.Person result = new pb.PersonOuterClass.Person(this);
        int from_bitField0_ = bitField0_;
        result.name_ = name_;
        result.age_ = age_;
        if (((bitField0_ & 0x00000001) != 0)) {
          emails_ = emails_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.emails_ = emails_;
        if (phonesBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0)) {
            phones_ = java.util.Collections.unmodifiableList(phones_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.phones_ = phones_;
        } else {
          result.phones_ = phonesBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pb.PersonOuterClass.Person) {
          return mergeFrom((pb.PersonOuterClass.Person)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pb.PersonOuterClass.Person other) {
        if (other == pb.PersonOuterClass.Person.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getAge() != 0) {
          setAge(other.getAge());
        }
        if (!other.emails_.isEmpty()) {
          if (emails_.isEmpty()) {
            emails_ = other.emails_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureEmailsIsMutable();
            emails_.addAll(other.emails_);
          }
          onChanged();
        }
        if (phonesBuilder_ == null) {
          if (!other.phones_.isEmpty()) {
            if (phones_.isEmpty()) {
              phones_ = other.phones_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensurePhonesIsMutable();
              phones_.addAll(other.phones_);
            }
            onChanged();
          }
        } else {
          if (!other.phones_.isEmpty()) {
            if (phonesBuilder_.isEmpty()) {
              phonesBuilder_.dispose();
              phonesBuilder_ = null;
              phones_ = other.phones_;
              bitField0_ = (bitField0_ & ~0x00000002);
              phonesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPhonesFieldBuilder() : null;
            } else {
              phonesBuilder_.addAllMessages(other.phones_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                name_ = input.readStringRequireUtf8();

                break;
              } // case 10
              case 16: {
                age_ = input.readInt32();

                break;
              } // case 16
              case 26: {
                java.lang.String s = input.readStringRequireUtf8();
                ensureEmailsIsMutable();
                emails_.add(s);
                break;
              } // case 26
              case 34: {
                pb.PersonOuterClass.PhoneNumber m =
                    input.readMessage(
                        pb.PersonOuterClass.PhoneNumber.parser(),
                        extensionRegistry);
                if (phonesBuilder_ == null) {
                  ensurePhonesIsMutable();
                  phones_.add(m);
                } else {
                  phonesBuilder_.addMessage(m);
                }
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <pre>
       * 姓名
       * </pre>
       *
       * <code>string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 姓名
       * </pre>
       *
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 姓名
       * </pre>
       *
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 姓名
       * </pre>
       *
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 姓名
       * </pre>
       *
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int age_ ;
      /**
       * <pre>
       * 年龄
       * </pre>
       *
       * <code>int32 age = 2;</code>
       * @return The age.
       */
      @java.lang.Override
      public int getAge() {
        return age_;
      }
      /**
       * <pre>
       * 年龄
       * </pre>
       *
       * <code>int32 age = 2;</code>
       * @param value The age to set.
       * @return This builder for chaining.
       */
      public Builder setAge(int value) {
        
        age_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 年龄
       * </pre>
       *
       * <code>int32 age = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAge() {
        
        age_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringList emails_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureEmailsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          emails_ = new com.google.protobuf.LazyStringArrayList(emails_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <pre>
       * 电子邮件
       * </pre>
       *
       * <code>repeated string emails = 3;</code>
       * @return A list containing the emails.
       */
      public com.google.protobuf.ProtocolStringList
          getEmailsList() {
        return emails_.getUnmodifiableView();
      }
      /**
       * <pre>
       * 电子邮件
       * </pre>
       *
       * <code>repeated string emails = 3;</code>
       * @return The count of emails.
       */
      public int getEmailsCount() {
        return emails_.size();
      }
      /**
       * <pre>
       * 电子邮件
       * </pre>
       *
       * <code>repeated string emails = 3;</code>
       * @param index The index of the element to return.
       * @return The emails at the given index.
       */
      public java.lang.String getEmails(int index) {
        return emails_.get(index);
      }
      /**
       * <pre>
       * 电子邮件
       * </pre>
       *
       * <code>repeated string emails = 3;</code>
       * @param index The index of the value to return.
       * @return The bytes of the emails at the given index.
       */
      public com.google.protobuf.ByteString
          getEmailsBytes(int index) {
        return emails_.getByteString(index);
      }
      /**
       * <pre>
       * 电子邮件
       * </pre>
       *
       * <code>repeated string emails = 3;</code>
       * @param index The index to set the value at.
       * @param value The emails to set.
       * @return This builder for chaining.
       */
      public Builder setEmails(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureEmailsIsMutable();
        emails_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 电子邮件
       * </pre>
       *
       * <code>repeated string emails = 3;</code>
       * @param value The emails to add.
       * @return This builder for chaining.
       */
      public Builder addEmails(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureEmailsIsMutable();
        emails_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 电子邮件
       * </pre>
       *
       * <code>repeated string emails = 3;</code>
       * @param values The emails to add.
       * @return This builder for chaining.
       */
      public Builder addAllEmails(
          java.lang.Iterable<java.lang.String> values) {
        ensureEmailsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, emails_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 电子邮件
       * </pre>
       *
       * <code>repeated string emails = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearEmails() {
        emails_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 电子邮件
       * </pre>
       *
       * <code>repeated string emails = 3;</code>
       * @param value The bytes of the emails to add.
       * @return This builder for chaining.
       */
      public Builder addEmailsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureEmailsIsMutable();
        emails_.add(value);
        onChanged();
        return this;
      }

      private java.util.List<pb.PersonOuterClass.PhoneNumber> phones_ =
        java.util.Collections.emptyList();
      private void ensurePhonesIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          phones_ = new java.util.ArrayList<pb.PersonOuterClass.PhoneNumber>(phones_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          pb.PersonOuterClass.PhoneNumber, pb.PersonOuterClass.PhoneNumber.Builder, pb.PersonOuterClass.PhoneNumberOrBuilder> phonesBuilder_;

      /**
       * <pre>
       * 电话
       * </pre>
       *
       * <code>repeated .pb.PhoneNumber phones = 4;</code>
       */
      public java.util.List<pb.PersonOuterClass.PhoneNumber> getPhonesList() {
        if (phonesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(phones_);
        } else {
          return phonesBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * 电话
       * </pre>
       *
       * <code>repeated .pb.PhoneNumber phones = 4;</code>
       */
      public int getPhonesCount() {
        if (phonesBuilder_ == null) {
          return phones_.size();
        } else {
          return phonesBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * 电话
       * </pre>
       *
       * <code>repeated .pb.PhoneNumber phones = 4;</code>
       */
      public pb.PersonOuterClass.PhoneNumber getPhones(int index) {
        if (phonesBuilder_ == null) {
          return phones_.get(index);
        } else {
          return phonesBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * 电话
       * </pre>
       *
       * <code>repeated .pb.PhoneNumber phones = 4;</code>
       */
      public Builder setPhones(
          int index, pb.PersonOuterClass.PhoneNumber value) {
        if (phonesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePhonesIsMutable();
          phones_.set(index, value);
          onChanged();
        } else {
          phonesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 电话
       * </pre>
       *
       * <code>repeated .pb.PhoneNumber phones = 4;</code>
       */
      public Builder setPhones(
          int index, pb.PersonOuterClass.PhoneNumber.Builder builderForValue) {
        if (phonesBuilder_ == null) {
          ensurePhonesIsMutable();
          phones_.set(index, builderForValue.build());
          onChanged();
        } else {
          phonesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 电话
       * </pre>
       *
       * <code>repeated .pb.PhoneNumber phones = 4;</code>
       */
      public Builder addPhones(pb.PersonOuterClass.PhoneNumber value) {
        if (phonesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePhonesIsMutable();
          phones_.add(value);
          onChanged();
        } else {
          phonesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * 电话
       * </pre>
       *
       * <code>repeated .pb.PhoneNumber phones = 4;</code>
       */
      public Builder addPhones(
          int index, pb.PersonOuterClass.PhoneNumber value) {
        if (phonesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePhonesIsMutable();
          phones_.add(index, value);
          onChanged();
        } else {
          phonesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * 电话
       * </pre>
       *
       * <code>repeated .pb.PhoneNumber phones = 4;</code>
       */
      public Builder addPhones(
          pb.PersonOuterClass.PhoneNumber.Builder builderForValue) {
        if (phonesBuilder_ == null) {
          ensurePhonesIsMutable();
          phones_.add(builderForValue.build());
          onChanged();
        } else {
          phonesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 电话
       * </pre>
       *
       * <code>repeated .pb.PhoneNumber phones = 4;</code>
       */
      public Builder addPhones(
          int index, pb.PersonOuterClass.PhoneNumber.Builder builderForValue) {
        if (phonesBuilder_ == null) {
          ensurePhonesIsMutable();
          phones_.add(index, builderForValue.build());
          onChanged();
        } else {
          phonesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * 电话
       * </pre>
       *
       * <code>repeated .pb.PhoneNumber phones = 4;</code>
       */
      public Builder addAllPhones(
          java.lang.Iterable<? extends pb.PersonOuterClass.PhoneNumber> values) {
        if (phonesBuilder_ == null) {
          ensurePhonesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, phones_);
          onChanged();
        } else {
          phonesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * 电话
       * </pre>
       *
       * <code>repeated .pb.PhoneNumber phones = 4;</code>
       */
      public Builder clearPhones() {
        if (phonesBuilder_ == null) {
          phones_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          phonesBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * 电话
       * </pre>
       *
       * <code>repeated .pb.PhoneNumber phones = 4;</code>
       */
      public Builder removePhones(int index) {
        if (phonesBuilder_ == null) {
          ensurePhonesIsMutable();
          phones_.remove(index);
          onChanged();
        } else {
          phonesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * 电话
       * </pre>
       *
       * <code>repeated .pb.PhoneNumber phones = 4;</code>
       */
      public pb.PersonOuterClass.PhoneNumber.Builder getPhonesBuilder(
          int index) {
        return getPhonesFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * 电话
       * </pre>
       *
       * <code>repeated .pb.PhoneNumber phones = 4;</code>
       */
      public pb.PersonOuterClass.PhoneNumberOrBuilder getPhonesOrBuilder(
          int index) {
        if (phonesBuilder_ == null) {
          return phones_.get(index);  } else {
          return phonesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * 电话
       * </pre>
       *
       * <code>repeated .pb.PhoneNumber phones = 4;</code>
       */
      public java.util.List<? extends pb.PersonOuterClass.PhoneNumberOrBuilder> 
           getPhonesOrBuilderList() {
        if (phonesBuilder_ != null) {
          return phonesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(phones_);
        }
      }
      /**
       * <pre>
       * 电话
       * </pre>
       *
       * <code>repeated .pb.PhoneNumber phones = 4;</code>
       */
      public pb.PersonOuterClass.PhoneNumber.Builder addPhonesBuilder() {
        return getPhonesFieldBuilder().addBuilder(
            pb.PersonOuterClass.PhoneNumber.getDefaultInstance());
      }
      /**
       * <pre>
       * 电话
       * </pre>
       *
       * <code>repeated .pb.PhoneNumber phones = 4;</code>
       */
      public pb.PersonOuterClass.PhoneNumber.Builder addPhonesBuilder(
          int index) {
        return getPhonesFieldBuilder().addBuilder(
            index, pb.PersonOuterClass.PhoneNumber.getDefaultInstance());
      }
      /**
       * <pre>
       * 电话
       * </pre>
       *
       * <code>repeated .pb.PhoneNumber phones = 4;</code>
       */
      public java.util.List<pb.PersonOuterClass.PhoneNumber.Builder> 
           getPhonesBuilderList() {
        return getPhonesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          pb.PersonOuterClass.PhoneNumber, pb.PersonOuterClass.PhoneNumber.Builder, pb.PersonOuterClass.PhoneNumberOrBuilder> 
          getPhonesFieldBuilder() {
        if (phonesBuilder_ == null) {
          phonesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              pb.PersonOuterClass.PhoneNumber, pb.PersonOuterClass.PhoneNumber.Builder, pb.PersonOuterClass.PhoneNumberOrBuilder>(
                  phones_,
                  ((bitField0_ & 0x00000002) != 0),
                  getParentForChildren(),
                  isClean());
          phones_ = null;
        }
        return phonesBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:pb.Person)
    }

    // @@protoc_insertion_point(class_scope:pb.Person)
    private static final pb.PersonOuterClass.Person DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pb.PersonOuterClass.Person();
    }

    public static pb.PersonOuterClass.Person getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Person>
        PARSER = new com.google.protobuf.AbstractParser<Person>() {
      @java.lang.Override
      public Person parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Person> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Person> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public pb.PersonOuterClass.Person getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PhoneNumberOrBuilder extends
      // @@protoc_insertion_point(interface_extends:pb.PhoneNumber)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 电话号码
     * </pre>
     *
     * <code>string number = 1;</code>
     * @return The number.
     */
    java.lang.String getNumber();
    /**
     * <pre>
     * 电话号码
     * </pre>
     *
     * <code>string number = 1;</code>
     * @return The bytes for number.
     */
    com.google.protobuf.ByteString
        getNumberBytes();

    /**
     * <pre>
     * 电话类型
     * </pre>
     *
     * <code>.pb.PhoneType type = 2;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <pre>
     * 电话类型
     * </pre>
     *
     * <code>.pb.PhoneType type = 2;</code>
     * @return The type.
     */
    pb.PersonOuterClass.PhoneType getType();
  }
  /**
   * Protobuf type {@code pb.PhoneNumber}
   */
  public static final class PhoneNumber extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:pb.PhoneNumber)
      PhoneNumberOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PhoneNumber.newBuilder() to construct.
    private PhoneNumber(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PhoneNumber() {
      number_ = "";
      type_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PhoneNumber();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return pb.PersonOuterClass.internal_static_pb_PhoneNumber_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return pb.PersonOuterClass.internal_static_pb_PhoneNumber_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              pb.PersonOuterClass.PhoneNumber.class, pb.PersonOuterClass.PhoneNumber.Builder.class);
    }

    public static final int NUMBER_FIELD_NUMBER = 1;
    private volatile java.lang.Object number_;
    /**
     * <pre>
     * 电话号码
     * </pre>
     *
     * <code>string number = 1;</code>
     * @return The number.
     */
    @java.lang.Override
    public java.lang.String getNumber() {
      java.lang.Object ref = number_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        number_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 电话号码
     * </pre>
     *
     * <code>string number = 1;</code>
     * @return The bytes for number.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNumberBytes() {
      java.lang.Object ref = number_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        number_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;
    /**
     * <pre>
     * 电话类型
     * </pre>
     *
     * <code>.pb.PhoneType type = 2;</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <pre>
     * 电话类型
     * </pre>
     *
     * <code>.pb.PhoneType type = 2;</code>
     * @return The type.
     */
    @java.lang.Override public pb.PersonOuterClass.PhoneType getType() {
      @SuppressWarnings("deprecation")
      pb.PersonOuterClass.PhoneType result = pb.PersonOuterClass.PhoneType.valueOf(type_);
      return result == null ? pb.PersonOuterClass.PhoneType.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(number_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, number_);
      }
      if (type_ != pb.PersonOuterClass.PhoneType.UNKNOWN.getNumber()) {
        output.writeEnum(2, type_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(number_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, number_);
      }
      if (type_ != pb.PersonOuterClass.PhoneType.UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof pb.PersonOuterClass.PhoneNumber)) {
        return super.equals(obj);
      }
      pb.PersonOuterClass.PhoneNumber other = (pb.PersonOuterClass.PhoneNumber) obj;

      if (!getNumber()
          .equals(other.getNumber())) return false;
      if (type_ != other.type_) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getNumber().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static pb.PersonOuterClass.PhoneNumber parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.PersonOuterClass.PhoneNumber parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.PersonOuterClass.PhoneNumber parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.PersonOuterClass.PhoneNumber parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.PersonOuterClass.PhoneNumber parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static pb.PersonOuterClass.PhoneNumber parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static pb.PersonOuterClass.PhoneNumber parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pb.PersonOuterClass.PhoneNumber parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static pb.PersonOuterClass.PhoneNumber parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static pb.PersonOuterClass.PhoneNumber parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static pb.PersonOuterClass.PhoneNumber parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static pb.PersonOuterClass.PhoneNumber parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(pb.PersonOuterClass.PhoneNumber prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code pb.PhoneNumber}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:pb.PhoneNumber)
        pb.PersonOuterClass.PhoneNumberOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return pb.PersonOuterClass.internal_static_pb_PhoneNumber_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return pb.PersonOuterClass.internal_static_pb_PhoneNumber_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                pb.PersonOuterClass.PhoneNumber.class, pb.PersonOuterClass.PhoneNumber.Builder.class);
      }

      // Construct using pb.PersonOuterClass.PhoneNumber.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        number_ = "";

        type_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return pb.PersonOuterClass.internal_static_pb_PhoneNumber_descriptor;
      }

      @java.lang.Override
      public pb.PersonOuterClass.PhoneNumber getDefaultInstanceForType() {
        return pb.PersonOuterClass.PhoneNumber.getDefaultInstance();
      }

      @java.lang.Override
      public pb.PersonOuterClass.PhoneNumber build() {
        pb.PersonOuterClass.PhoneNumber result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public pb.PersonOuterClass.PhoneNumber buildPartial() {
        pb.PersonOuterClass.PhoneNumber result = new pb.PersonOuterClass.PhoneNumber(this);
        result.number_ = number_;
        result.type_ = type_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof pb.PersonOuterClass.PhoneNumber) {
          return mergeFrom((pb.PersonOuterClass.PhoneNumber)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(pb.PersonOuterClass.PhoneNumber other) {
        if (other == pb.PersonOuterClass.PhoneNumber.getDefaultInstance()) return this;
        if (!other.getNumber().isEmpty()) {
          number_ = other.number_;
          onChanged();
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                number_ = input.readStringRequireUtf8();

                break;
              } // case 10
              case 16: {
                type_ = input.readEnum();

                break;
              } // case 16
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private java.lang.Object number_ = "";
      /**
       * <pre>
       * 电话号码
       * </pre>
       *
       * <code>string number = 1;</code>
       * @return The number.
       */
      public java.lang.String getNumber() {
        java.lang.Object ref = number_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          number_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 电话号码
       * </pre>
       *
       * <code>string number = 1;</code>
       * @return The bytes for number.
       */
      public com.google.protobuf.ByteString
          getNumberBytes() {
        java.lang.Object ref = number_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          number_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 电话号码
       * </pre>
       *
       * <code>string number = 1;</code>
       * @param value The number to set.
       * @return This builder for chaining.
       */
      public Builder setNumber(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        number_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 电话号码
       * </pre>
       *
       * <code>string number = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearNumber() {
        
        number_ = getDefaultInstance().getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 电话号码
       * </pre>
       *
       * <code>string number = 1;</code>
       * @param value The bytes for number to set.
       * @return This builder for chaining.
       */
      public Builder setNumberBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        number_ = value;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <pre>
       * 电话类型
       * </pre>
       *
       * <code>.pb.PhoneType type = 2;</code>
       * @return The enum numeric value on the wire for type.
       */
      @java.lang.Override public int getTypeValue() {
        return type_;
      }
      /**
       * <pre>
       * 电话类型
       * </pre>
       *
       * <code>.pb.PhoneType type = 2;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 电话类型
       * </pre>
       *
       * <code>.pb.PhoneType type = 2;</code>
       * @return The type.
       */
      @java.lang.Override
      public pb.PersonOuterClass.PhoneType getType() {
        @SuppressWarnings("deprecation")
        pb.PersonOuterClass.PhoneType result = pb.PersonOuterClass.PhoneType.valueOf(type_);
        return result == null ? pb.PersonOuterClass.PhoneType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * 电话类型
       * </pre>
       *
       * <code>.pb.PhoneType type = 2;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(pb.PersonOuterClass.PhoneType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 电话类型
       * </pre>
       *
       * <code>.pb.PhoneType type = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:pb.PhoneNumber)
    }

    // @@protoc_insertion_point(class_scope:pb.PhoneNumber)
    private static final pb.PersonOuterClass.PhoneNumber DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new pb.PersonOuterClass.PhoneNumber();
    }

    public static pb.PersonOuterClass.PhoneNumber getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PhoneNumber>
        PARSER = new com.google.protobuf.AbstractParser<PhoneNumber>() {
      @java.lang.Override
      public PhoneNumber parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PhoneNumber> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PhoneNumber> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public pb.PersonOuterClass.PhoneNumber getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_Person_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_Person_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_pb_PhoneNumber_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_pb_PhoneNumber_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014person.proto\022\002pb\"T\n\006Person\022\014\n\004name\030\001 \001" +
      "(\t\022\013\n\003age\030\002 \001(\005\022\016\n\006emails\030\003 \003(\t\022\037\n\006phone" +
      "s\030\004 \003(\0132\017.pb.PhoneNumber\":\n\013PhoneNumber\022" +
      "\016\n\006number\030\001 \001(\t\022\033\n\004type\030\002 \001(\0162\r.pb.Phone" +
      "Type*8\n\tPhoneType\022\013\n\007UNKNOWN\020\000\022\n\n\006MOBILE" +
      "\020\001\022\010\n\004HOME\020\002\022\010\n\004WORK\020\003B\007Z\005./;pbb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_pb_Person_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_pb_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_Person_descriptor,
        new java.lang.String[] { "Name", "Age", "Emails", "Phones", });
    internal_static_pb_PhoneNumber_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_pb_PhoneNumber_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_pb_PhoneNumber_descriptor,
        new java.lang.String[] { "Number", "Type", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
